# @package _global_.simulation
model_repo: 'https://github.com/g-levine/quadrapet_v3_description'
model_branch: 'master'
original_model_path: 'quadrapet_v3_description/description/mujoco_xml/quadrapet_v3_complete.mjx.position.no_body.self_collision.two_iterations.xml'
model_path: "quadrapet_v3_description/description/mujoco_xml/model_with_obstacles.xml"

# Model body names
upper_leg_body_names: ["leg_front_r_2", "leg_front_l_2", "leg_back_r_2", "leg_back_l_2"]
lower_leg_body_names: ["leg_front_r_3", "leg_front_l_3", "leg_back_r_3", "leg_back_l_3"]
foot_site_names: [
  "leg_front_r_3_foot_site",
  "leg_front_l_3_foot_site",
  "leg_back_r_3_foot_site",
  "leg_back_l_3_foot_site",
]
torso_name: "base_link"

# Physics settings
foot_radius: 0.02
max_contact_points: 20
max_geom_pairs: 20
physics_dt: 0.004

# Joint limits (will be loaded from model)
joint_upper_limits: []
joint_lower_limits: []