build: 
    cargo build
    cargo zigbuild --target aarch64-unknown-linux-gnu --release

sync: build
    rsync -hazvP target/aarch64-unknown-linux-gnu/release pi@quadrapet.local:/home/pi/quadrapetv3-monorepo/quadrapet-rs/target/aarch64-unknown-linux-gnu/

run-ssh:
    DISPLAY=:0 ./target/release/quadrapet-rs